// Translation System for IBS Mobile Shop
// Supports English (en) and Arabic (ar) languages

const translations = {
    // Login Page
    login: {
        en: {
            title: "Mobile Shop Management",
            username: "Username:",
            password: "Password:",
            login: "Login",
            error: "Invalid username or password"
        },
        ar: {
            title: "إدارة متجر الهواتف المحمولة",
            username: "اسم المستخدم:",
            password: "كلمة المرور:",
            login: "دخول",
            error: "اسم المستخدم أو كلمة المرور غير صحيحة"
        }
    },

    // Dashboard Navigation
    navigation: {
        en: {
            dashboard: "Dashboard",
            inventory: "Inventory",
            sales: "Sales",
            staff: "Staff",
            reports: "Reports",
            income: "Income",
            payment: "Payment",
            logout: "Logout",
            welcome: "Welcome",
            receipt: "Receipt",
            customers: "Customers"
        },
        ar: {
            dashboard: "لوحة التحكم",
            inventory: "المخزون",
            sales: "المبيعات",
            staff: "الموظفين",
            reports: "التقارير",
            income: "الدخل",
            payment: "المدفوعات",
            logout: "تسجيل الخروج",
            welcome: "مرحباً",
            receipt: "الإيصال",
            customers: "العملاء"
        }
    },

    // Inventory Management
    inventory: {
        en: {
            title: "Inventory Management",
            addProduct: "Add Product",
            editProduct: "Edit Product",
            deleteProduct: "Delete Product",
            search: "🔍 Search Products:",
            code: "Code",
            product: "Product",
            productCode: "Product Code:",
            brand: "Brand",
            model: "Model",
            description: "Description",
            price: "Price",
            stock: "Stock",
            stockQuantity: "Stock Quantity:",
            category: "Category",
            color: "Color",
            serial: "Serial/IMEI",
            serialNumber: "Serial Number:",
            serialHelp: "Unique serial number for tracking",
            supplier: "Supplier",
            selectSupplier: "Select Supplier",
            supplierHelp: "Choose supplier for this product",
            purchasePrice: "Purchase Price (Cost)",
            purchasePriceHelp: "The cost price you pay to suppliers",
            minPrice: "Minimum Selling Price",
            minPriceHelp: "Staff cannot sell below this price",
            suggestedPrice: "Suggested Selling Price",
            suggestedPriceHelp: "Default price shown in receipts (can be changed)",
            status: "Status",
            id: "ID",
            date: "Date",
            imei: "IMEI",
            unitDetails: "Product Unit Details",
            customerName: "Customer Name",
            customerPhone: "Customer Phone",
            walkIn: "Walk-In",
            stockDetails: "Stock Details",
            actions: "Actions",
            autoGenerated: "Product code will be automatically created when you save",
            colorHelp: "Product color (e.g., Black, White, Blue)",
            hasImei: "Has IMEI:",
            imeiHelp: "Does this product have IMEI?",
            minStock: "Minimum Stock:",
            minStockHelp: "Optional: Set minimum stock level for alerts",
            selectCategory: "Select Category",
            phones: "Phones",
            airpods: "AirPods",
            watch: "Watch",
            accessories: "Accessories",
            tablets: "Tablets",
            categoryHelp: "Choose product category",
            barcode: "Barcode",
            scanBarcode: "📷 Scan Barcode",
            generateBarcode: "📊 Generate",
            barcodeGenerated: "Barcode generated successfully",
            productFound: "Product Found",
            productNotFound: "Product not found for barcode",
            save: "Save",
            cancel: "Cancel",
            delete: "Delete",
            confirmDelete: "Are you sure you want to delete this product?",
            productAdded: "Product added successfully!",
            productUpdated: "Product updated successfully!",
            productDeleted: "Product deleted successfully!",
            scanning: "Scanning barcode...",
            productSpecs: "Product Specifications",
            productClassification: "Product Classification & Identity",
            pricingInventory: "Pricing & Inventory",
            visualsNotes: "Visuals & Notes",
            modelName: "Model Name",
            lowStockAlert: "Low Stock Alert",
            trackingReq: "Tracking Requirements",
            imeiTracking: "IMEI Tracking",
            serialTracking: "Serial Number Tracking",
            autoGeneratedCode: "Product Code (Auto-generated)",
            pendingClassification: "Pending Classification",
            initialStock: "Initial Stock (Quantity)",
            costPrice: "Cost Price",
            minSalePrice: "Minimum Sale Price",
            marketPrice: "Market Price",
            additionalDetails: "Additional Details",
            descriptionPlaceholder: "Description, specifications, or internal notes...",
            productImage: "Product Image",
            clickToUpload: "Click to upload",
            clearForm: "Clear Form",
            loading: "Loading...",
            selectBrand: "Select Brand",
            success: "Success!",
            productAddedSuccess: "Product added successfully.",
            great: "Great!"
        },
        ar: {
            title: "إدارة المخزون",
            addProduct: "إضافة منتج",
            editProduct: "تعديل منتج",
            deleteProduct: "حذف منتج",
            search: "🔍 البحث عن المنتجات:",
            code: "الكود",
            product: "المنتج",
            productCode: "كود المنتج:",
            brand: "العلامة التجارية",
            model: "الموديل",
            description: "الوصف",
            price: "السعر",
            stock: "المخزون",
            stockQuantity: "الكمية في المخزون:",
            category: "الفئة",
            color: "اللون",
            serial: "الرقم التسلسلي/IMEI",
            serialNumber: "الرقم التسلسلي:",
            serialHelp: "رقم تسلسلي فريد للتتبع",
            supplier: "المورد",
            selectSupplier: "اختر المورد",
            supplierHelp: "اختر المورد لهذا المنتج",
            purchasePrice: "سعر الشراء (التكلفة)",
            purchasePriceHelp: "سعر التكلفة الذي تدفعه للموردين",
            minPrice: "الحد الأدنى لسعر البيع",
            minPriceHelp: "لا يمكن للموظفين البيع أقل من هذا السعر",
            suggestedPrice: "سعر البيع المقترح",
            suggestedPriceHelp: "السعر الافتراضي المعروض في الفواتير (يمكن تغييره)",
            status: "الحالة",
            id: "المعرف",
            date: "التاريخ",
            imei: "IMEI",
            unitDetails: "تفاصيل وحدة المنتج",
            customerName: "اسم العميل",
            customerPhone: "رقم هاتف العميل",
            walkIn: "عميل عابر",
            stockDetails: "تفاصيل المخزون",
            actions: "الإجراءات",
            autoGenerated: "سيتم إنشاء كود المنتج تلقائياً عند الحفظ",
            colorHelp: "لون المنتج (مثال: أسود، أبيض، أزرق)",
            hasImei: "هل يحتوي على IMEI:",
            imeiHelp: "هل هذا المنتج يحتوي على IMEI؟",
            minStock: "الحد الأدنى للمخزون:",
            minStockHelp: "اختياري: تعيين الحد الأدنى للمخزون للتنبيهات",
            selectCategory: "اختر الفئة",
            phones: "هواتف",
            airpods: "AirPods",
            watch: "ساعات",
            accessories: "إكسسوارات",
            tablets: "أجهزة لوحية",
            categoryHelp: "اختر فئة المنتج",
            barcode: "الباركود",
            scanBarcode: "📷 مسح الباركود",
            generateBarcode: "📊 توليد",
            barcodeGenerated: "تم توليد الباركود بنجاح",
            productFound: "تم العثور على المنتج",
            productNotFound: "لم يتم العثور على منتج لهذا الباركود",
            save: "حفظ",
            cancel: "إلغاء",
            delete: "حذف",
            confirmDelete: "هل أنت متأكد من حذف هذا المنتج؟",
            productAdded: "تم إضافة المنتج بنجاح!",
            productUpdated: "تم تحديث المنتج بنجاح!",
            productDeleted: "تم حذف المنتج بنجاح!",
            scanning: "جاري مسح الباركود...",
            productSpecs: "مواصفات المنتج",
            productClassification: "تصنيف المنتج وهويته",
            pricingInventory: "التسعير والمخزون",
            visualsNotes: "المرئيات والملاحظات",
            modelName: "اسم الموديل",
            lowStockAlert: "تنبيه المخزون المنخفض",
            trackingReq: "متطلبات التتبع",
            imeiTracking: "تتبع IMEI",
            serialTracking: "تتبع الرقم التسلسلي",
            autoGeneratedCode: "كود المنتج (توليد تلقائي)",
            pendingClassification: "في انتظار التصنيف",
            initialStock: "المخزون الأولي (الكمية)",
            costPrice: "سعر التكلفة",
            minSalePrice: "الحد الأدنى لسعر البيع",
            marketPrice: "سعر السوق",
            additionalDetails: "تفاصيل إضافية",
            descriptionPlaceholder: "الوصف، المواصفات، أو ملاحظات داخلية...",
            productImage: "صورة المنتج",
            clickToUpload: "انقر للتحميل",
            clearForm: "مسح النموذج",
            loading: "جاري التحميل...",
            selectBrand: "اختر العلامة التجارية",
            success: "تم بنجاح!",
            productAddedSuccess: "تم إضافة المنتج بنجاح.",
            great: "ممتاز!"
        }
    },

    // Sales Management
    sales: {
        en: {
            title: "Sales Management",
            newSale: "New Sale",
            receipt: "Receipt",
            createReceipt: "Create Receipt",
            customerInfo: "Customer Information",
            customerName: "Customer Name:",
            customerNamePlaceholder: "Enter customer name",
            customerPhone: "Customer Phone:",
            customerPhonePlaceholder: "Enter phone number",
            selectProduct: "Select Product:",
            chooseProduct: "Choose a product...",
            sellingPrice: "Selling Price:",
            quantity: "Quantity:",
            quantityPlaceholder: "1",
            addToReceipt: "Add to Receipt",
            receiptItems: "Receipt Items",
            noItemsAdded: "No items added yet",
            total: "Total",
            completeSale: "Complete Sale",
            clearReceipt: "Clear",
            searchReceipt: "Search receipt...",
            receiptNumber: "Receipt #",
            date: "Date",
            staff: "Staff",
            customer: "Customer",
            totalAmount: "Total Amount",
            actions: "Actions",
            viewDetails: "View Details",
            print: "Print",
            searchProducts: "Search products...",
            subtotal: "Subtotal",
            paymentMethod: "Payment Method",
            cash: "Cash",
            card: "Card",
            card: "Card",
            saleCompleted: "Sale Completed!",
            receiptGenerated: "Receipt # has been generated successfully.",
            totalAmountPaid: "Total Amount Paid",
            gotIt: "Got it",
            receiptInformation: "Receipt Information",
            receiptNumberLabel: "Receipt Number:",
            paymentSummary: "Payment Summary",
            printReceipt: "🖨️ Print Receipt",
            close: "Close",
            noProductSelected: "No product selected",
            grandTotal: "Grand Total:",
            method: "Method",
            amount: "Amount",
            reference: "Ref (optional)",
            addPayment: "➕ Add Payment",
            paid: "Paid",
            remaining: "Remaining",
            selectedProduct: "Selected Product",
            clearReceipt: "🗑️ Clear Receipt",
            completed: "Completed",
            returned: "Returned",
            partiallyReturned: "Partially Returned",
            confirmReturnTitle: "Confirm Return",
            confirmReturnMessage: "Are you sure you want to process this return? Selected items will be restored to stock.",
            confirmReturnBtn: "Confirm Return",
            cancelReturnBtn: "Cancel",
            returnSuccessTitle: "Return Processed",
            returnSuccessMessage: "Return processed successfully! Inventory and statistics have been updated.",
            closeBtn: "Close",
            netItems: "Net Items",
            returnedQty: "Returned Qty",
            originalPurchase: "Original Purchase",
            returnedItems: "Returned Items",
            adjustedReceipt: "Final Adjusted Receipt",
            originalTotal: "Original Total",
            returnCredit: "Return Credit",
            netTotal: "Net Total"
        },
        ar: {
            title: "إدارة المبيعات",
            newSale: "بيع جديد",
            receipt: "الإيصال",
            createReceipt: "إنشاء إيصال",
            customerInfo: "معلومات العميل",
            customerName: "اسم العميل:",
            customerNamePlaceholder: "أدخل اسم العميل",
            customerPhone: "هاتف العميل:",
            customerPhonePlaceholder: "أدخل رقم الهاتف",
            selectProduct: "اختر المنتج:",
            chooseProduct: "اختر منتج...",
            sellingPrice: "سعر البيع:",
            quantity: "الكمية:",
            quantityPlaceholder: "1",
            addToReceipt: "إضافة للإيصال",
            receiptItems: "عناصر الإيصال",
            noItemsAdded: "لم تتم إضافة عناصر بعد",
            total: "الإجمالي",
            completeSale: "إتمام البيع",
            clearReceipt: "مسح",
            searchReceipt: "البحث عن إيصال...",
            receiptNumber: "رقم الإيصال #",
            date: "التاريخ",
            staff: "الموظف",
            customer: "العميل",
            totalAmount: "المبلغ الإجمالي",
            actions: "الإجراءات",
            viewDetails: "عرض التفاصيل",
            print: "طباعة",
            searchProducts: "البحث عن المنتجات...",
            subtotal: "المجموع",
            paymentMethod: "طريقة الدفع",
            cash: "نقدي",
            card: "بطاقة",
            saleCompleted: "تم إتمام البيع بنجاح!",
            receiptDetails: "تفاصيل الإيصال",
            receiptInformation: "معلومات الإيصال",
            receiptNumberLabel: "رقم الإيصال:",
            paymentSummary: "ملخص الدفع",
            printReceipt: "🖨️ طباعة الإيصال",
            close: "إغلاق",
            saleCompleted: "تم إتمام البيع!",
            receiptGenerated: "تم إنشاء الإيصال # بنجاح.",
            totalAmountPaid: "إجمالي المبلغ المدفوع",
            gotIt: "حسنًا",
            noProductSelected: "لم يتم اختيار منتج",
            grandTotal: "الإجمالي الكلي:",
            method: "الطريقة",
            amount: "المبلغ",
            reference: "المرجع (اختياري)",
            addPayment: "➕ إضافة دفع",
            paid: "المدفوع",
            remaining: "المتبقي",
            selectedProduct: "المنتج المختار",
            clearReceipt: "🗑️ مسح الإيصال",
            salesToday: "مبيعات اليوم",
            revenueToday: "إيرادات اليوم",
            salesMonth: "مبيعات الشهر",
            revenueMonth: "إيرادات الشهر",
            soldUnits: "الوحدات المباعة",
            returnedItems: "العناصر المرتجعة",
            revenueByMethod: "الإيرادات حسب طريقة الدفع (هذا الشهر)",
            searchFilters: "البحث المتقدم والتصنيفات",
            resetFilters: "إعادة ضبط الفلاتر",
            barcodePlaceholder: "امسح أو اكتب الباركود...",
            phonePlaceholder: "ابحث برقم الهاتف...",
            idPlaceholder: "المعرف أو رقم الإيصال",
            searchResults: "تحديث النتائج",
            invoiceReceipt: "الفاتورة / الإيصال",
            customerDetails: "تفاصيل العميل",
            dateTime: "التاريخ والوقت",
            items: "العناصر",
            status: "الحالة",
            completed: "مكتمل",
            returned: "مرتجع",
            partiallyReturned: "مرتجع جزئي",
            viewDetailsTitle: "عرض التفاصيل",
            printReceiptTitle: "طباعة إيصال POS",
            returnItemsTitle: "إرجاع العناصر",
            confirmReturnTitle: "تأكيد الإرجاع",
            confirmReturnMessage: "هل أنت متأكد من رغبتك في إتمام عملية الإرجاع هذه؟ سيتم استعادة العناصر المختارة إلى المخزون.",
            confirmReturnBtn: "تأكيد الإرجاع",
            cancelReturnBtn: "إلغاء",
            returnSuccessTitle: "تمت معالجة الإرجاع",
            returnSuccessMessage: "تمت معالجة الإرجاع بنجاح! تم تحديث المخزون والإحصائيات.",
            closeBtn: "إغلاق",
            netItems: "صافي العناصر",
            returnedQty: "الكمية المرتجعة",
            originalPurchase: "الطلب الأصلي",
            returnedItems: "العناصر المرتجعة",
            adjustedReceipt: "الإيصال النهائي المعدل",
            originalTotal: "الإجمالي الأصلي",
            returnCredit: "رصيد الإرجاع",
            netTotal: "صافي الإجمالي"
        }
    },

    // Reports Management
    reports: {
        en: {
            title: "Reports",
            printReports: "Print Reports",
            todaysSalesReport: "Today's Sales Report",
            monthlySalesReport: "Monthly Sales Report",
            inventoryReport: "Inventory Report",
            profitLossReport: "Profit & Loss Report",
            lowStockReport: "Low Stock Report",
            generateReport: "Generate Report",
            exportToPDF: "Export to PDF",
            exportToExcel: "Export to Excel",
            dateRange: "Date Range",
            fromDate: "From Date",
            toDate: "To Date",
            totalRevenue: "Total Revenue",
            totalProfit: "Total Profit",
            totalExpenses: "Total Expenses",
            netProfit: "Net Profit",
            lowStockItems: "Low Stock Items",
            outOfStockItems: "Out of Stock Items",
            todaySales: "Today's Sales",
            todayProfit: "Today's Profit",
            monthSales: "This Month Sales",
            monthProfit: "This Month Profit",
            totalProducts: "Total Products",
            lowStock: "Low Stock Items"
        },
        ar: {
            title: "التقارير",
            printReports: "طباعة التقارير",
            todaysSalesReport: "تقرير مبيعات اليوم",
            monthlySalesReport: "تقرير المبيعات الشهري",
            inventoryReport: "تقرير المخزون",
            profitLossReport: "تقرير الأرباح والخسائر",
            lowStockReport: "تقرير المخزون المنخفض",
            generateReport: "توليد تقرير",
            exportToPDF: "تصدير إلى PDF",
            exportToExcel: "تصدير إلى Excel",
            dateRange: "نطاق التاريخ",
            fromDate: "من تاريخ",
            toDate: "إلى تاريخ",
            totalRevenue: "إجمالي الإيرادات",
            totalProfit: "إجمالي الأرباح",
            totalExpenses: "إجمالي المصروفات",
            netProfit: "صافي الربح",
            lowStockItems: "عناصر المخزون المنخفض",
            outOfStockItems: "عناصر غير متوفرة في المخزون",
            todaySales: "مبيعات اليوم",
            todayProfit: "ربح اليوم",
            monthSales: "مبيعات هذا الشهر",
            monthProfit: "ربح هذا الشهر",
            totalProducts: "إجمالي المنتجات",
            lowStock: "عناصر المخزون المنخفض"
        }
    },

    // Staff Management

    staff: {
        en: {
            title: "Staff Management",
            addStaff: "Add Staff",
            editStaff: "Edit Staff",
            deleteStaff: "Delete Staff",
            search: "Search staff...",
            name: "Name",
            username: "Username",
            password: "Password",
            email: "Email",
            phone: "Phone",
            role: "Role",
            status: "Status",
            actions: "Actions",
            active: "Active",
            inactive: "Inactive",
            currentStaff: "Current Staff",
            searchStaff: "🔍 Search Staff:",
            staffList: "Staff List",
            admin: "Admin",
            staff: "Staff",
            edit: "Edit",
            delete: "Delete",
            confirmDelete: "Are you sure you want to delete this staff member?"
        },
        ar: {
            title: "إدارة الموظفين",
            addStaff: "إضافة موظف",
            editStaff: "تعديل موظف",
            deleteStaff: "حذف موظف",
            search: "البحث عن موظفين...",
            name: "الاسم",
            username: "اسم المستخدم",
            password: "كلمة المرور",
            email: "البريد الإلكتروني",
            phone: "الهاتف",
            role: "الدور",
            status: "الحالة",
            actions: "الإجراءات",
            active: "نشط",
            inactive: "غير نشط",
            currentStaff: "الموظفون الحاليون",
            searchStaff: "🔍 البحث عن موظف:",
            staffList: "قائمة الموظفين",
            admin: "مدير",
            staff: "موظف",
            edit: "تعديل",
            delete: "حذف",
            confirmDelete: "هل أنت متأكد من حذف هذا الموظف؟"
        }
    },

    // Income Management
    income: {
        en: {
            title: "Income Management",
            addNewIncome: "Add New Income Entry",
            incomeEntries: "Income Entries",
            price: "Price",
            description: "Description",
            date: "Date",
            actions: "Actions",
            amount: "Amount",
            totalIncome: "Total Income",
            addIncomeEntry: "Add Income Entry",
            enterIncomeAmount: "Enter income amount",
            describeIncome: "Describe the source of income...",
            amountGreaterThanZero: "Amount must be greater than 0",
            provideIncomeDetails: "Provide details about this income entry",
            delete: "Delete",
            confirmDelete: "Are you sure you want to delete this income entry?"
        },
        ar: {
            title: "إدارة الدخل",
            addNewIncome: "إضافة دخلة دخل جديدة",
            incomeEntries: "مدخلات الدخل",
            price: "السعر",
            description: "الوصف",
            date: "التاريخ",
            actions: "الإجراءات",
            amount: "المبلغ",
            totalIncome: "إجمالي الدخل",
            addIncomeEntry: "إضافة دخلة دخل",
            enterIncomeAmount: "أدخل مبلغ الدخل",
            describeIncome: "صف مصدر الدخل...",
            amountGreaterThanZero: "يجب أن يكون المبلغ أكبر من صفر",
            provideIncomeDetails: "قدم تفاصيل حول دخلة الدخل هذه",
            delete: "حذف",
            confirmDelete: "هل أنت متأكد من حذف دخلة الدخل هذه؟"
        }
    },

    // Payment Management
    payment: {
        en: {
            title: "Payment Management",
            addNewPayment: "Add New Payment Entry",
            paymentEntries: "Payment Entries",
            amount: "Amount",
            description: "Description",
            date: "Date",
            actions: "Actions",
            totalPayments: "Total Payments",
            addPaymentEntry: "Add Payment Entry",
            enterPaymentAmount: "Enter payment amount",
            describePayment: "Describe the payment purpose...",
            amountGreaterThanZero: "Amount must be greater than 0",
            providePaymentDetails: "Provide details about this payment",
            delete: "Delete",
            confirmDelete: "Are you sure you want to delete this payment entry?"
        },
        ar: {
            title: "إدارة المدفوعات",
            addNewPayment: "إضافة مدفوعة جديدة",
            paymentEntries: "المدفوعات",
            amount: "المبلغ",
            description: "الوصف",
            date: "التاريخ",
            actions: "الإجراءات",
            totalPayments: "إجمالي المدفوعات",
            addPaymentEntry: "إضافة مدفوعة",
            enterPaymentAmount: "أدخل مبلغ الدفعة",
            describePayment: "صف غرض الدفعة...",
            amountGreaterThanZero: "يجب أن يكون المبلغ أكبر من صفر",
            providePaymentDetails: "قدم تفاصيل حول هذه الدفعة",
            delete: "حذف",
            confirmDelete: "هل أنت متأكد من حذف هذه الدفعة؟"
        }
    },

    // Customers Management
    customers: {
        en: {
            title: "Customer Tab",
            search: "Search Customers",
            list: "Customer List",
            id: "ID",
            name: "Name",
            phone: "Phone",
            email: "Email",
            totalPurchases: "Total Purchases",
            searchPlaceholder: "Search by name, phone, or email...",
            noCustomersFound: "No customers found matching your search",
            editCustomer: "Edit Customer",
            address: "Address",
            updateCustomer: "Update Customer",
            updatedSuccess: "Customer updated successfully!",
            deletedSuccess: "Customer deleted successfully!",
            deleteConfirm: "Are you sure you want to delete this customer?",
            errorUpdating: "Error updating customer. Please try again.",
            errorDeleting: "Error deleting customer. Please try again."
        },
        ar: {
            title: "علامة تبويب العملاء",
            search: "البحث عن العملاء",
            list: "قائمة العملاء",
            id: "المعرف",
            name: "الاسم",
            phone: "الهاتف",
            email: "البريد الإلكتروني",
            totalPurchases: "إجمالي المشتريات",
            searchPlaceholder: "بحث بالاسم، الهاتف، أو البريد...",
            noCustomersFound: "لم يتم العثور على عملاء مطابقين لبحثك",
            editCustomer: "تعديل العميل",
            address: "العنوان",
            updateCustomer: "تحديث العميل",
            updatedSuccess: "تم تحديث العميل بنجاح!",
            deletedSuccess: "تم حذف العميل بنجاح!",
            deleteConfirm: "هل أنت متأكد من حذف هذا العميل؟",
            errorUpdating: "خطأ أثناء تحديث العميل. يرجى المحاولة مرة أخرى.",
            errorDeleting: "خطأ أثناء حذف العميل. يرجى المحاولة مرة أخرى."
        }
    },

    // Common Messages
    common: {
        en: {
            loading: "Loading...",
            error: "Error",
            success: "Success",
            warning: "Warning",
            info: "Information",
            confirm: "Confirm",
            yes: "Yes",
            no: "No",
            ok: "OK",
            cancel: "Cancel",
            close: "Close",
            save: "Save",
            delete: "Delete",
            edit: "Edit",
            add: "Add",
            search: "Search",
            reset: "Reset",
            filter: "Filter",
            clear: "Clear",
            refresh: "Refresh",
            export: "Export",
            print: "Print",
            back: "Back",
            next: "Next",
            previous: "Previous",
            page: "Page",
            of: "of",
            records: "records",
            noRecords: "No records found",
            createdAt: "Created At",
            actions: "Actions",
            selectOption: "Please select an option",
            requiredField: "This field is required",
            invalidEmail: "Please enter a valid email address",
            invalidPhone: "Please enter a valid phone number",
            minLength: "Minimum length is",
            maxLength: "Maximum length is",
            numericOnly: "Numbers only",
            positiveNumber: "Please enter a positive number"
        },
        ar: {
            loading: "جاري التحميل...",
            error: "خطأ",
            success: "نجح",
            warning: "تحذير",
            info: "معلومات",
            confirm: "تأكيد",
            yes: "نعم",
            no: "لا",
            ok: "موافق",
            cancel: "إلغاء",
            close: "إغلاق",
            save: "حفظ",
            delete: "حذف",
            edit: "تعديل",
            add: "إضافة",
            search: "بحث",
            reset: "إعادة ضبط",
            filter: "تصفية",
            clear: "مسح",
            refresh: "تحديث",
            export: "تصدير",
            print: "طباعة",
            back: "رجوع",
            next: "التالي",
            previous: "السابق",
            page: "صفحة",
            of: "من",
            records: "سجلات",
            noRecords: "لا توجد سجلات",
            createdAt: "تاريخ الإنشاء",
            actions: "الإجراءات",
            selectOption: "الرجاء اختيار خيار",
            requiredField: "هذا الحقل مطلوب",
            invalidEmail: "الرجاء إدخال بريد إلكتروني صحيح",
            invalidPhone: "الرجاء إدخال رقم هاتف صحيح",
            minLength: "الحد الأدنى للطول هو",
            maxLength: "الحد الأقصى للطول هو",
            numericOnly: "أرقام فقط",
            positiveNumber: "الرجاء إدخال رقم موجب"
        }
    }
};

// Language Management Functions
class LanguageManager {
    constructor() {
        this.currentLang = localStorage.getItem('language') || 'en';
        this.fallbackLang = 'en';
    }

    // Get current language
    getCurrentLanguage() {
        return this.currentLang;
    }

    // Set current language
    setLanguage(lang) {
        this.currentLang = lang;
        localStorage.setItem('language', lang);
        this.applyLanguage(lang);
    }

    // Toggle between languages
    toggleLanguage() {
        const newLang = this.currentLang === 'en' ? 'ar' : 'en';
        this.setLanguage(newLang);
        return newLang;
    }

    // Get translation for a specific key
    translate(category, key) {
        try {
            if (translations[category] &&
                translations[category][this.currentLang] &&
                translations[category][this.currentLang][key]) {
                return translations[category][this.currentLang][key];
            }

            // Fallback to English if current language doesn't have the translation
            if (translations[category] &&
                translations[category][this.fallbackLang] &&
                translations[category][this.fallbackLang][key]) {
                return translations[category][this.fallbackLang][key];
            }

            return key; // Return the key itself if no translation found
        } catch (error) {
            console.warn('Translation error:', error);
            return key;
        }
    }

    // Apply language to the entire page
    applyLanguage(lang) {
        // Update HTML lang attribute
        const htmlElement = document.documentElement;
        if (htmlElement) {
            htmlElement.setAttribute('lang', lang);
        }

        // Update body direction
        const body = document.body;
        if (body) {
            if (lang === 'ar') {
                body.setAttribute('dir', 'rtl');
                body.classList.add('rtl');
            } else {
                body.setAttribute('dir', 'ltr');
                body.classList.remove('rtl');
            }
        }

        // Update all translatable elements
        document.querySelectorAll('[data-translate]').forEach(element => {
            const translateAttr = element.getAttribute('data-translate');
            const [category, key] = translateAttr.split('.');

            if (category && key) {
                const translation = this.translate(category, key);
                if (translation) {
                    element.textContent = translation;
                }

                // Also translate placeholders if they exist
                if (element.hasAttribute('placeholder')) {
                    const placeholderKey = element.getAttribute('data-translate-placeholder');
                    if (placeholderKey) {
                        const [pCat, pKey] = placeholderKey.split('.');
                        const pTranslation = this.translate(pCat, pKey);
                        if (pTranslation) {
                            element.setAttribute('placeholder', pTranslation);
                        }
                    }
                }
            }
        });

        // Specifically handle placeholders for inputs that don't use textContent
        document.querySelectorAll('[data-translate-placeholder]').forEach(element => {
            const translateAttr = element.getAttribute('data-translate-placeholder');
            const [category, key] = translateAttr.split('.');

            if (category && key) {
                const translation = this.translate(category, key);
                if (translation) {
                    element.setAttribute('placeholder', translation);
                }
            }
        });

        // Update language toggle button
        const langText = document.querySelector('.lang-text');
        if (langText) {
            langText.textContent = lang === 'en' ? 'EG' : 'AR';
        }

        const langIcon = document.querySelector('.lang-icon');
        if (langIcon) {
            langIcon.textContent = lang === 'en' ? '🇪🇬' : '🌐';
        }

        // Update page title if available
        const titleElement = document.querySelector('title[data-translate]');
        if (titleElement) {
            const [category, key] = titleElement.getAttribute('data-translate').split('.');
            const translation = this.translate(category, key);
            if (translation) {
                document.title = translation;
            }
        }
    }

    // Initialize language system
    init() {
        this.applyLanguage(this.currentLang);
    }
}

// Create global language manager instance
const langManager = new LanguageManager();

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { translations, LanguageManager, langManager };
}
