// Translation System for IBS Mobile Shop
// Supports English (en) and Arabic (ar) languages

const translations = {
    // Login Page
    login: {
        en: {
            title: "Mobile Shop Management",
            username: "Username:",
            password: "Password:",
            login: "Login",
            error: "Invalid username or password"
        },
        ar: {
            title: "إدارة متجر الهواتف المحمولة",
            username: "اسم المستخدم:",
            password: "كلمة المرور:",
            login: "دخول",
            error: "اسم المستخدم أو كلمة المرور غير صحيحة"
        }
    },

    // Dashboard Navigation
    navigation: {
        en: {
            dashboard: "Dashboard",
            inventory: "Inventory",
            sales: "Sales",
            staff: "Staff",
            reports: "Reports",
            income: "Income",
            payment: "Payment",
            logout: "Logout",
            welcome: "Welcome",
            receipt: "Receipt",
            customers: "Customers",
            financial: "Financial"
        },
        ar: {
            dashboard: "لوحة التحكم",
            inventory: "المخزون",
            sales: "المبيعات",
            staff: "الموظفين",
            reports: "التقارير",
            income: "الدخل",
            payment: "المدفوعات",
            logout: "تسجيل الخروج",
            welcome: "مرحباً",
            receipt: "الإيصال",
            customers: "العملاء",
            financial: "المالية"
        }
    },

    // Inventory Management
    inventory: {
        en: {
            title: "Inventory Management",
            addProduct: "Add Product",
            editProduct: "Edit Product",
            deleteProduct: "Delete Product",
            search: "🔍 Search Products:",
            code: "Code",
            product: "Product",
            productCode: "Product Code:",
            brand: "Brand",
            model: "Model",
            description: "Description",
            price: "Price",
            stock: "Stock",
            stockQuantity: "Stock Quantity:",
            category: "Category",
            color: "Color",
            serial: "Serial/IMEI",
            serialNumber: "Serial Number:",
            serialHelp: "Unique serial number for tracking",
            supplier: "Supplier",
            selectSupplier: "Select Supplier",
            supplierHelp: "Choose supplier for this product",
            purchasePrice: "Purchase Price (Cost)",
            purchasePriceHelp: "The cost price you pay to suppliers",
            minPrice: "Minimum Selling Price",
            minPriceHelp: "Staff cannot sell below this price",
            suggestedPrice: "Suggested Selling Price",
            suggestedPriceHelp: "Default price shown in receipts (can be changed)",
            status: "Status",
            id: "ID",
            date: "Date",
            imei: "IMEI",
            unitDetails: "Product Unit Details",
            customerName: "Customer Name",
            customerPhone: "Customer Phone",
            walkIn: "Walk-In",
            stockDetails: "Stock Details",
            actions: "Actions",
            autoGenerated: "Product code will be automatically created when you save",
            colorHelp: "Product color (e.g., Black, White, Blue)",
            hasImei: "Has IMEI:",
            imeiHelp: "Does this product have IMEI?",
            minStock: "Minimum Stock:",
            minStockHelp: "Optional: Set minimum stock level for alerts",
            selectCategory: "Select Category",
            phones: "Phones",
            airpods: "AirPods",
            watch: "Watch",
            accessories: "Accessories",
            tablets: "Tablets",
            categoryHelp: "Choose product category",
            barcode: "Barcode",
            scanBarcode: "📷 Scan Barcode",
            generateBarcode: "📊 Generate",
            barcodeGenerated: "Barcode generated successfully",
            productFound: "Product Found",
            productNotFound: "Product not found for barcode",
            save: "Save",
            cancel: "Cancel",
            delete: "Delete",
            confirmDelete: "Are you sure you want to delete this product?",
            productAdded: "Product added successfully!",
            productUpdated: "Product updated successfully!",
            productDeleted: "Product deleted successfully!",
            scanning: "Scanning barcode...",
            productSpecs: "Product Specifications",
            productClassification: "Product Classification & Identity",
            pricingInventory: "Pricing & Inventory",
            visualsNotes: "Visuals & Notes",
            modelName: "Model Name",
            lowStockAlert: "Low Stock Alert",
            trackingReq: "Tracking Requirements",
            imeiTracking: "IMEI Tracking",
            serialTracking: "Serial Number Tracking",
            autoGeneratedCode: "Product Code (Auto-generated)",
            pendingClassification: "Pending Classification",
            initialStock: "Initial Stock (Quantity)",
            costPrice: "Cost Price",
            minSalePrice: "Minimum Sale Price",
            marketPrice: "Market Price",
            additionalDetails: "Additional Details",
            descriptionPlaceholder: "Description, specifications, or internal notes...",
            productImage: "Product Image",
            clickToUpload: "Click to upload",
            clearForm: "Clear Form",
            loading: "Loading...",
            selectBrand: "Select Brand",
            success: "Success!",
            productAddedSuccess: "Product added successfully.",
            great: "Great!"
        },
        ar: {
            title: "إدارة المخزون",
            addProduct: "إضافة منتج",
            editProduct: "تعديل منتج",
            deleteProduct: "حذف منتج",
            search: "🔍 البحث عن المنتجات:",
            code: "الكود",
            product: "المنتج",
            productCode: "كود المنتج:",
            brand: "العلامة التجارية",
            model: "الموديل",
            description: "الوصف",
            price: "السعر",
            stock: "المخزون",
            stockQuantity: "الكمية في المخزون:",
            category: "الفئة",
            color: "اللون",
            serial: "الرقم التسلسلي/IMEI",
            serialNumber: "الرقم التسلسلي:",
            serialHelp: "رقم تسلسلي فريد للتتبع",
            supplier: "المورد",
            selectSupplier: "اختر المورد",
            supplierHelp: "اختر المورد لهذا المنتج",
            purchasePrice: "سعر الشراء (التكلفة)",
            purchasePriceHelp: "سعر التكلفة الذي تدفعه للموردين",
            minPrice: "الحد الأدنى لسعر البيع",
            minPriceHelp: "لا يمكن للموظفين البيع أقل من هذا السعر",
            suggestedPrice: "سعر البيع المقترح",
            suggestedPriceHelp: "السعر الافتراضي المعروض في الفواتير (يمكن تغييره)",
            status: "الحالة",
            id: "المعرف",
            date: "التاريخ",
            imei: "IMEI",
            unitDetails: "تفاصيل وحدة المنتج",
            customerName: "اسم العميل",
            customerPhone: "رقم هاتف العميل",
            walkIn: "عميل عابر",
            stockDetails: "تفاصيل المخزون",
            actions: "الإجراءات",
            autoGenerated: "سيتم إنشاء كود المنتج تلقائياً عند الحفظ",
            colorHelp: "لون المنتج (مثال: أسود، أبيض، أزرق)",
            hasImei: "هل يحتوي على IMEI:",
            imeiHelp: "هل هذا المنتج يحتوي على IMEI؟",
            minStock: "الحد الأدنى للمخزون:",
            minStockHelp: "اختياري: تعيين الحد الأدنى للمخزون للتنبيهات",
            selectCategory: "اختر الفئة",
            phones: "هواتف",
            airpods: "AirPods",
            watch: "ساعات",
            accessories: "إكسسوارات",
            tablets: "أجهزة لوحية",
            categoryHelp: "اختر فئة المنتج",
            barcode: "الباركود",
            scanBarcode: "📷 مسح الباركود",
            generateBarcode: "📊 توليد",
            barcodeGenerated: "تم توليد الباركود بنجاح",
            productFound: "تم العثور على المنتج",
            productNotFound: "لم يتم العثور على منتج لهذا الباركود",
            save: "حفظ",
            cancel: "إلغاء",
            delete: "حذف",
            confirmDelete: "هل أنت متأكد من حذف هذا المنتج؟",
            productAdded: "تم إضافة المنتج بنجاح!",
            productUpdated: "تم تحديث المنتج بنجاح!",
            productDeleted: "تم حذف المنتج بنجاح!",
            scanning: "جاري مسح الباركود...",
            productSpecs: "مواصفات المنتج",
            productClassification: "تصنيف المنتج وهويته",
            pricingInventory: "التسعير والمخزون",
            visualsNotes: "المرئيات والملاحظات",
            modelName: "اسم الموديل",
            lowStockAlert: "تنبيه المخزون المنخفض",
            trackingReq: "متطلبات التتبع",
            imeiTracking: "تتبع IMEI",
            serialTracking: "تتبع الرقم التسلسلي",
            autoGeneratedCode: "كود المنتج (توليد تلقائي)",
            pendingClassification: "في انتظار التصنيف",
            initialStock: "المخزون الأولي (الكمية)",
            costPrice: "سعر التكلفة",
            minSalePrice: "الحد الأدنى لسعر البيع",
            marketPrice: "سعر السوق",
            additionalDetails: "تفاصيل إضافية",
            descriptionPlaceholder: "الوصف، المواصفات، أو ملاحظات داخلية...",
            productImage: "صورة المنتج",
            clickToUpload: "انقر للتحميل",
            clearForm: "مسح النموذج",
            loading: "جاري التحميل...",
            selectBrand: "اختر العلامة التجارية",
            success: "تم بنجاح!",
            productAddedSuccess: "تم إضافة المنتج بنجاح.",
            great: "ممتاز!"
        }
    },

    // Sales Management
    sales: {
        en: {
            title: "Sales Management",
            newSale: "New Sale",
            receipt: "Receipt",
            createReceipt: "Create Receipt",
            customerInfo: "Customer Information",
            customerName: "Customer Name:",
            customerNamePlaceholder: "Enter customer name",
            customerPhone: "Customer Phone:",
            customerPhonePlaceholder: "Enter phone number",
            selectProduct: "Select Product:",
            chooseProduct: "Choose a product...",
            sellingPrice: "Selling Price:",
            quantity: "Quantity:",
            quantityPlaceholder: "1",
            addToReceipt: "Add to Receipt",
            receiptItems: "Receipt Items",
            noItemsAdded: "No items added yet",
            total: "Total",
            completeSale: "Complete Sale",
            clearReceipt: "Clear",
            searchReceipt: "Search receipt...",
            receiptNumber: "Receipt #",
            date: "Date",
            staff: "Staff",
            customer: "Customer",
            totalAmount: "Total Amount",
            actions: "Actions",
            viewDetails: "View Details",
            print: "Print",
            searchProducts: "Search products...",
            subtotal: "Subtotal",
            paymentMethod: "Payment Method",
            cash: "Cash",
            card: "Card",
            card: "Card",
            saleCompleted: "Sale Completed!",
            receiptGenerated: "Receipt # has been generated successfully.",
            totalAmountPaid: "Total Amount Paid",
            gotIt: "Got it",
            receiptInformation: "Receipt Information",
            receiptNumberLabel: "Receipt Number:",
            paymentSummary: "Payment Summary",
            printReceipt: "🖨️ Print Receipt",
            close: "Close",
            noProductSelected: "No product selected",
            grandTotal: "Grand Total:",
            method: "Method",
            amount: "Amount",
            reference: "Ref (optional)",
            addPayment: "➕ Add Payment",
            paid: "Paid",
            remaining: "Remaining",
            selectedProduct: "Selected Product",
            clearReceipt: "🗑️ Clear Receipt",
            completed: "Completed",
            returned: "Returned",
            partiallyReturned: "Partially Returned",
            confirmReturnTitle: "Confirm Return",
            confirmReturnMessage: "Are you sure you want to process this return? Selected items will be restored to stock.",
            confirmReturnBtn: "Confirm Return",
            cancelReturnBtn: "Cancel",
            returnSuccessTitle: "Return Processed",
            returnSuccessMessage: "Return processed successfully! Inventory and statistics have been updated.",
            closeBtn: "Close",
            netItems: "Net Items",
            returnedQty: "Returned Qty",
            originalPurchase: "Original Purchase",
            returnedItems: "Returned Items",
            adjustedReceipt: "Final Adjusted Receipt",
            originalTotal: "Original Total",
            returnCredit: "Return Credit",
            netTotal: "Net Total"
        },
        ar: {
            title: "إدارة المبيعات",
            newSale: "بيع جديد",
            receipt: "الإيصال",
            createReceipt: "إنشاء إيصال",
            customerInfo: "معلومات العميل",
            customerName: "اسم العميل:",
            customerNamePlaceholder: "أدخل اسم العميل",
            customerPhone: "هاتف العميل:",
            customerPhonePlaceholder: "أدخل رقم الهاتف",
            selectProduct: "اختر المنتج:",
            chooseProduct: "اختر منتج...",
            sellingPrice: "سعر البيع:",
            quantity: "الكمية:",
            quantityPlaceholder: "1",
            addToReceipt: "إضافة للإيصال",
            receiptItems: "عناصر الإيصال",
            noItemsAdded: "لم تتم إضافة عناصر بعد",
            total: "الإجمالي",
            completeSale: "إتمام البيع",
            clearReceipt: "مسح",
            searchReceipt: "البحث عن إيصال...",
            receiptNumber: "رقم الإيصال #",
            date: "التاريخ",
            staff: "الموظف",
            customer: "العميل",
            totalAmount: "المبلغ الإجمالي",
            actions: "الإجراءات",
            viewDetails: "عرض التفاصيل",
            print: "طباعة",
            searchProducts: "البحث عن المنتجات...",
            subtotal: "المجموع",
            paymentMethod: "طريقة الدفع",
            cash: "نقدي",
            card: "بطاقة",
            saleCompleted: "تم إتمام البيع بنجاح!",
            receiptDetails: "تفاصيل الإيصال",
            receiptInformation: "معلومات الإيصال",
            receiptNumberLabel: "رقم الإيصال:",
            paymentSummary: "ملخص الدفع",
            printReceipt: "🖨️ طباعة الإيصال",
            close: "إغلاق",
            saleCompleted: "تم إتمام البيع!",
            receiptGenerated: "تم إنشاء الإيصال # بنجاح.",
            totalAmountPaid: "إجمالي المبلغ المدفوع",
            gotIt: "حسنًا",
            noProductSelected: "لم يتم اختيار منتج",
            grandTotal: "الإجمالي الكلي:",
            method: "الطريقة",
            amount: "المبلغ",
            reference: "المرجع (اختياري)",
            addPayment: "➕ إضافة دفع",
            paid: "المدفوع",
            remaining: "المتبقي",
            selectedProduct: "المنتج المختار",
            clearReceipt: "🗑️ مسح الإيصال",
            salesToday: "مبيعات اليوم",
            revenueToday: "إيرادات اليوم",
            salesMonth: "مبيعات الشهر",
            revenueMonth: "إيرادات الشهر",
            soldUnits: "الوحدات المباعة",
            returnedItems: "العناصر المرتجعة",
            revenueByMethod: "الإيرادات حسب طريقة الدفع (هذا الشهر)",
            searchFilters: "البحث المتقدم والتصنيفات",
            resetFilters: "إعادة ضبط الفلاتر",
            barcodePlaceholder: "امسح أو اكتب الباركود...",
            phonePlaceholder: "ابحث برقم الهاتف...",
            idPlaceholder: "المعرف أو رقم الإيصال",
            searchResults: "تحديث النتائج",
            invoiceReceipt: "الفاتورة / الإيصال",
            customerDetails: "تفاصيل العميل",
            dateTime: "التاريخ والوقت",
            items: "العناصر",
            status: "الحالة",
            completed: "مكتمل",
            returned: "مرتجع",
            partiallyReturned: "مرتجع جزئي",
            viewDetailsTitle: "عرض التفاصيل",
            printReceiptTitle: "طباعة إيصال POS",
            returnItemsTitle: "إرجاع العناصر",
            confirmReturnTitle: "تأكيد الإرجاع",
            confirmReturnMessage: "هل أنت متأكد من رغبتك في إتمام عملية الإرجاع هذه؟ سيتم استعادة العناصر المختارة إلى المخزون.",
            confirmReturnBtn: "تأكيد الإرجاع",
            cancelReturnBtn: "إلغاء",
            returnSuccessTitle: "تمت معالجة الإرجاع",
            returnSuccessMessage: "تمت معالجة الإرجاع بنجاح! تم تحديث المخزون والإحصائيات.",
            closeBtn: "إغلاق",
            netItems: "صافي العناصر",
            returnedQty: "الكمية المرتجعة",
            originalPurchase: "الطلب الأصلي",
            returnedItems: "العناصر المرتجعة",
            adjustedReceipt: "الإيصال النهائي المعدل",
            originalTotal: "الإجمالي الأصلي",
            returnCredit: "رصيد الإرجاع",
            netTotal: "صافي الإجمالي"
        }
    },

    // Reports Management
    reports: {
        en: {
            title: "Operational Reports",
            dateFrom: "From Date",
            dateTo: "To Date",
            apply: "Apply Filter",
            reset: "Reset Range",
            printReport: "Print Branch Report",
            totalTransactions: "Total Transactions",
            totalRevenue: "Total Revenue",
            soldUnits: "Total Sold Units",
            cashCollected: "Cash Collected",
            returnsCount: "Returns Count",
            avgInvoice: "Avg Invoice Value",
            salesTrend: "Sales Trend",
            paymentBreakdown: "Payment Breakdown",
            topProducts: "Top Selling Products",
            revenue: "Revenue",
            returnsSummary: "Returns Summary",
            returnedSales: "Returned Sales",
            returnedUnits: "Returned Units",
            returnedAmount: "Returned Amount"
        },
        ar: {
            title: "تقارير العمليات",
            dateFrom: "من تاريخ",
            dateTo: "إلى تاريخ",
            apply: "تطبيق الفلتر",
            reset: "إعادة تعيين",
            printReport: "طباعة تقرير الفرع",
            totalTransactions: "إجمالي العمليات",
            totalRevenue: "إجمالي الإيرادات",
            soldUnits: "إجمالي الوحدات المباعة",
            cashCollected: "النقدية المحصلة",
            returnsCount: "عدد المرتجعات",
            avgInvoice: "متوسط قيمة الفاتورة",
            salesTrend: "اتجاه المبيعات",
            paymentBreakdown: "تحليل طرق الدفع",
            topProducts: "المنتجات الأكثر مبيعاً",
            revenue: "الإيرادات",
            returnsSummary: "ملخص المرتجعات",
            returnedSales: "المبيعات المرتجعة",
            returnedUnits: "الوحدات المرتجعة",
            returnedAmount: "إجمالي المرتجعات"
        }
    },

    // Staff Management

    staff: {
        en: {
            title: "Staff Management",
            addStaff: "Add Staff",
            editStaff: "Edit Staff",
            deleteStaff: "Delete Staff",
            search: "Search staff...",
            name: "Name",
            username: "Username",
            password: "Password",
            email: "Email",
            phone: "Phone",
            role: "Role",
            status: "Status",
            actions: "Actions",
            active: "Active",
            inactive: "Inactive",
            currentStaff: "Current Staff",
            searchStaff: "🔍 Search Staff:",
            staffList: "Staff List",
            admin: "Admin",
            staff: "Staff",
            edit: "Edit",
            delete: "Delete",
            confirmDelete: "Are you sure you want to delete this staff member?",
            activeStaff: "Active Staff",
            inactiveStaff: "Inactive Staff",
            totalStaff: "Total Staff",
            sendMessage: "Send Message to All Staff",
            writeMessage: "Write your message for all staff members...",
            sendSms: "🚀 Send via Twilio",
            smsSent: "Messages sent successfully! 🎉",
            smsError: "Failed to send some messages.",
            smsPartial: "Some messages failed to send. Please check audit logs."
        },
        ar: {
            title: "إدارة الموظفين",
            addStaff: "إضافة موظف",
            editStaff: "تعديل موظف",
            deleteStaff: "حذف موظف",
            search: "البحث عن موظفين...",
            name: "الاسم",
            username: "اسم المستخدم",
            password: "كلمة المرور",
            email: "البريد الإلكتروني",
            phone: "الهاتف",
            role: "الدور",
            status: "الحالة",
            actions: "الإجراءات",
            active: "نشط",
            inactive: "غير نشط",
            currentStaff: "الموظفون الحاليون",
            searchStaff: "🔍 البحث عن موظف:",
            staffList: "قائمة الموظفين",
            admin: "مدير",
            staff: "موظف",
            edit: "تعديل",
            delete: "حذف",
            confirmDelete: "هل أنت متأكد من حذف هذا الموظف؟",
            activeStaff: "الموظفون النشطون",
            inactiveStaff: "غير النشطين",
            totalStaff: "إجمالي الموظفين",
            sendMessage: "إرسال رسالة للكل",
            writeMessage: "اكتب رسالتك لجميع الموظفين...",
            sendSms: "🚀 إرسال عبر Twilio",
            smsSent: "تم إرسال الرسائل بنجاح! 🎉",
            smsError: "فشل إرسال بعض الرسائل.",
            smsPartial: "فشل إرسال بعض الرسائل. يرجى مراجعة سجلات التدقيق."
        }
    },

    // Income Management
    income: {
        en: {
            title: "Operating Revenue",
            arabicTitle: "الإيرادات التشغيلية",
            addNewIncome: "Add New Income Entry",
            incomeEntries: "Income Entries",
            price: "Price",
            description: "Description",
            date: "Date",
            actions: "Actions",
            amount: "Amount",
            totalIncome: "Total Income",
            addIncomeEntry: "Add Income Entry",
            enterIncomeAmount: "Enter income amount",
            describeIncome: "Describe the source of income...",
            amountGreaterThanZero: "Amount must be greater than 0",
            provideIncomeDetails: "Provide details about this income entry",
            delete: "Delete",
            confirmDelete: "Are you sure you want to delete this income entry?",
            print: "Print Receipt"
        },
        ar: {
            title: "الإيرادات التشغيلية",
            addNewIncome: "إضافة إيراد جديد",
            incomeEntries: "مدخلات الدخل",
            price: "السعر",
            description: "الوصف",
            date: "التاريخ",
            actions: "الإجراءات",
            amount: "المبلغ",
            totalIncome: "إجمالي الدخل",
            addIncomeEntry: "إضافة دخل",
            enterIncomeAmount: "أدخل مبلغ الدخل",
            describeIncome: "صف مصدر الدخل...",
            amountGreaterThanZero: "يجب أن يكون المبلغ أكبر من صفر",
            provideIncomeDetails: "قدم تفاصيل حول دخلة الدخل هذه",
            delete: "حذف",
            confirmDelete: "هل أنت متأكد من حذف دخلة الدخل هذه؟",
            print: "طباعة إيصال"
        }
    },

    // Payment Management
    payment: {
        en: {
            title: "Operating Expenses",
            arabicTitle: "المصروفات التشغيلية",
            addNewPayment: "Add New Expense Entry",
            paymentEntries: "Expense Entries",
            amount: "Amount",
            description: "Description",
            date: "Date",
            actions: "Actions",
            totalPayments: "Total Expenses",
            addPaymentEntry: "Add Expense Entry",
            enterPaymentAmount: "Enter amount",
            describePayment: "Describe the expense...",
            amountGreaterThanZero: "Amount must be greater than 0",
            providePaymentDetails: "Provide details about this expense",
            delete: "Delete",
            confirmDelete: "Are you sure you want to delete this expense entry?",
            print: "Print Receipt",
            expenseType: "Expense Type",
            generalExpense: "General Expense",
            productDamage: "Product Damage",
            product: "Product",
            quantity: "Quantity",
            searchProduct: "Search product...",
            addDamage: "Add Damage"
        },
        ar: {
            title: "المصروفات التشغيلية",
            addNewPayment: "إضافة مصروفات عمومية",
            paymentEntries: "المصروفات",
            amount: "المبلغ",
            description: "الوصف",
            date: "التاريخ",
            actions: "الإجراءات",
            totalPayments: "إجمالي المصروفات",
            addPaymentEntry: "إضافة مصروفات",
            enterPaymentAmount: "أدخل المبلغ",
            describePayment: "صف المصروف...",
            amountGreaterThanZero: "يجب أن يكون المبلغ أكبر من صفر",
            providePaymentDetails: "قدم تفاصيل حول هذه المصروفات",
            delete: "حذف",
            confirmDelete: "هل أنت متأكد من حذف هذه المصروفات؟",
            print: "طباعة إيصال",
            expenseType: "نوع المصروف",
            generalExpense: "مصروف عام",
            productDamage: "هالك منتجات",
            product: "المنتج",
            quantity: "الكمية",
            searchProduct: "ابحث عن منتج...",
            addDamage: "إضافة هالك"
        }
    },

    // Customers Management
    customers: {
        en: {
            title: "Customer Tab",
            search: "Search Customers",
            list: "Customer List",
            id: "ID",
            name: "Name",
            phone: "Phone",
            email: "Email",
            totalPurchases: "Total Purchases",
            searchPlaceholder: "Search by name, phone, or email...",
            noCustomersFound: "No customers found matching your search",
            editCustomer: "Edit Customer",
            address: "Address",
            updateCustomer: "Update Customer",
            updatedSuccess: "Customer updated successfully!",
            deletedSuccess: "Customer deleted successfully!",
            deleteConfirm: "Are you sure you want to delete this customer?",
            errorUpdating: "Error updating customer. Please try again.",
            errorDeleting: "Error deleting customer. Please try again.",
            totalCustomers: "Total Customers",
            totalRevenue: "Total Revenue",
            newThisMonth: "New This Month",
            topCustomer: "Top Customer",
            addCustomer: "Add Customer",
            saveCustomer: "Save Customer",
            searchByName: "Search by name...",
            searchByPhone: "Search by phone...",
            searchByEmail: "Search by email...",
            namePlaceholder: "Customer full name...",
            phonePlaceholder: "Phone number...",
            emailPlaceholder: "Email address...",
            addressPlaceholder: "Address...",
            searchResults: "Search Results",
            sendMessage: "Send Message to All Customers",
            writeMessage: "Write your message for all customers...",
            sendSms: "🚀 Send via Twilio",
            smsSent: "Messages sent successfully! 🎉",
            smsError: "Failed to send some messages.",
            smsPartial: "Some messages failed to send. Please check audit logs."
        },
        ar: {
            title: "علامة تبويب العملاء",
            search: "البحث عن العملاء",
            list: "قائمة العملاء",
            id: "المعرف",
            name: "الاسم",
            phone: "الهاتف",
            email: "البريد الإلكتروني",
            totalPurchases: "إجمالي المشتريات",
            searchPlaceholder: "بحث بالاسم، الهاتف، أو البريد...",
            noCustomersFound: "لم يتم العثور على عملاء مطابقين لبحثك",
            editCustomer: "تعديل العميل",
            address: "العنوان",
            updateCustomer: "تحديث العميل",
            updatedSuccess: "تم تحديث العميل بنجاح!",
            deletedSuccess: "تم حذف العميل بنجاح!",
            deleteConfirm: "هل أنت متأكد من حذف هذا العميل؟",
            errorUpdating: "خطأ أثناء تحديث العميل. يرجى المحاولة مرة أخرى.",
            errorDeleting: "خطأ أثناء حذف العميل. يرجى المحاولة مرة أخرى.",
            totalCustomers: "إجمالي العملاء",
            totalRevenue: "إجمالي الإيرادات",
            newThisMonth: "جديد هذا الشهر",
            topCustomer: "أفضل عميل",
            addCustomer: "إضافة عميل",
            saveCustomer: "حفظ العميل",
            searchByName: "بحث بالاسم...",
            searchByPhone: "بحث بالهاتف...",
            searchByEmail: "بحث بالبريد...",
            namePlaceholder: "اسم العميل بالكامل...",
            phonePlaceholder: "رقم الهاتف...",
            emailPlaceholder: "البريد الإلكتروني...",
            addressPlaceholder: "العنوان...",
            searchResults: "نتائج البحث",
            sendMessage: "إرسال رسالة لجميع العملاء",
            writeMessage: "اكتب رسالتك لجميع العملاء...",
            sendSms: "🚀 إرسال عبر Twilio",
            smsSent: "تم إرسال الرسائل بنجاح! 🎉",
            smsError: "فشل إرسال بعض الرسائل.",
            smsPartial: "فشل إرسال بعض الرسائل. يرجى مراجعة سجلات التدقيق."
        }
    },

    // Common Messages
    common: {
        en: {
            loading: "Loading...",
            error: "Error",
            success: "Success",
            warning: "Warning",
            info: "Information",
            confirm: "Confirm",
            yes: "Yes",
            no: "No",
            ok: "OK",
            cancel: "Cancel",
            close: "Close",
            save: "Save",
            delete: "Delete",
            edit: "Edit",
            add: "Add",
            search: "Search",
            reset: "Reset",
            filter: "Filter",
            clear: "Clear",
            refresh: "Refresh",
            export: "Export",
            print: "Print",
            back: "Back",
            next: "Next",
            previous: "Previous",
            page: "Page",
            of: "of",
            records: "records",
            noRecords: "No records found",
            createdAt: "Created At",
            actions: "Actions",
            selectOption: "Please select an option",
            requiredField: "This field is required",
            invalidEmail: "Please enter a valid email address",
            invalidPhone: "Please enter a valid phone number",
            minLength: "Minimum length is",
            maxLength: "Maximum length is",
            numericOnly: "Numbers only",
            positiveNumber: "Please enter a positive number"
        },
        ar: {
            loading: "جاري التحميل...",
            error: "خطأ",
            success: "نجح",
            warning: "تحذير",
            info: "معلومات",
            confirm: "تأكيد",
            yes: "نعم",
            no: "لا",
            ok: "موافق",
            cancel: "إلغاء",
            close: "إغلاق",
            save: "حفظ",
            delete: "حذف",
            edit: "تعديل",
            add: "إضافة",
            search: "بحث",
            reset: "إعادة ضبط",
            filter: "تصفية",
            clear: "مسح",
            refresh: "تحديث",
            export: "تصدير",
            print: "طباعة",
            back: "رجوع",
            next: "التالي",
            previous: "السابق",
            page: "صفحة",
            of: "من",
            records: "سجلات",
            noRecords: "لا توجد سجلات",
            createdAt: "تاريخ الإنشاء",
            actions: "الإجراءات",
            selectOption: "الرجاء اختيار خيار",
            requiredField: "هذا الحقل مطلوب",
            invalidEmail: "الرجاء إدخال بريد إلكتروني صحيح",
            invalidPhone: "الرجاء إدخال رقم هاتف صحيح",
            minLength: "الحد الأدنى للطول هو",
            maxLength: "الحد الأقصى للطول هو",
            numericOnly: "أرقام فقط",
            positiveNumber: "الرجاء إدخال رقم موجب"
        }
    },

    // Owner Dashboard
    owner: {
        en: {
            title: "Global Enterprise Control",
            subtitle: "Global performance across all branches",
            stats: {
                totalBranches: "Total Branches",
                monthlyRevenue: "Monthly Revenue",
                monthlyUnits: "Units Sold (Month)",
                monthlyProfit: "Net Profit (Month)",
                transactions: "Total Transactions",
                lowStock: "Low Stock Items",
                totalReturns: "Total Returns",
                bestPerforming: "Best Performing Branch"
            },
            menu: {
                dashboard: "Overview",
                branches: "Branch Control",
                masterData: "Master Data",
                products: "Global Stock",
                analytics: "BI Analytics",
                access: "Access Control",
                settings: "System Config",
                logout: "System Logout"
            },
            branches: {
                title: "Branch Control Panel",
                add: "Add New Branch",
                table: {
                    name: "Branch Name",
                    location: "Location",
                    revenue: "Revenue",
                    units: "Units",
                    status: "Status",
                    actions: "Control"
                }
            },
            products: {
                title: "Global Product Master",
                table: {
                    name: "Product & Model",
                    branch: "Storage Branch",
                    purchase: "Cost",
                    minPrice: "Min Price",
                    market: "Market Price",
                    stock: "Stock",
                    status: "Lock Status"
                }
            },
            common: {
                egp: "EGP",
                units: "Units",
                active: "Active",
                disabled: "Disabled",
                locked: "Locked",
                save: "Save Changes",
                cancel: "Cancel Action",
                add: "Add New"
            },
            masterData: {
                title: "Master Data Management",
                categories: "Categories",
                brands: "Brands",
                suppliers: "Suppliers",
                addNew: "Add New Entity"
            },
            accessControl: {
                title: "Access Control",
                createAdmin: "Create New Admin"
            }
        },
        ar: {
            title: "مركز التحكم العالمي للمؤسسة",
            subtitle: "الأداء العام عبر جميع الفروع",
            stats: {
                totalBranches: "إجمالي الفروع",
                monthlyRevenue: "إيرادات الشهر",
                monthlyUnits: "الوحدات المباعة (الشهر)",
                monthlyProfit: "صافي الربح (الشهر)",
                transactions: "إجمالي العمليات",
                lowStock: "نواقص المخزون",
                totalReturns: "إجمالي المرتجعات",
                bestPerforming: "أفضل فرع أداءً"
            },
            menu: {
                dashboard: "نظرة عامة",
                branches: "التحكم في الفروع",
                masterData: "البيانات الأساسية",
                products: "المخزون العالمي",
                analytics: "تحليلات الأعمال",
                access: "صلاحيات الوصول",
                settings: "إعدادات النظام",
                logout: "تسجيل الخروج"
            },
            branches: {
                title: "لوحة التحكم في الفروع",
                add: "إضافة فرع جديد",
                table: {
                    name: "اسم الفرع",
                    location: "الموقع",
                    revenue: "الإيرادات",
                    units: "الوحدات",
                    status: "الحالة",
                    actions: "تحكم"
                }
            },
            products: {
                title: "سجل المنتجات العالمي",
                table: {
                    name: "المنتج والموديل",
                    branch: "فرع التخزين",
                    purchase: "التكلفة",
                    minPrice: "أقل سعر",
                    market: "سعر السوق",
                    stock: "المخزون",
                    status: "حالة القفل"
                }
            },
            common: {
                egp: "ج.م",
                units: "وحدة",
                active: "نشط",
                disabled: "معطل",
                locked: "مقفل",
                save: "حفظ التغييرات",
                cancel: "إلغاء الإجراء",
                add: "إضافة جديد"
            },
            masterData: {
                title: "إدارة البيانات الأساسية",
                categories: "الفئات",
                brands: "العلامات التجارية",
                suppliers: "الموردين",
                addNew: "إضافة كيان جديد"
            },
            accessControl: {
                title: "صلاحيات الوصول",
                createAdmin: "إنشاء مدير جديد"
            }
        }
    }
};

// Language Management Functions
class LanguageManager {
    constructor() {
        this.currentLang = localStorage.getItem('language') || 'en';
        this.fallbackLang = 'en';
    }

    // Get current language
    getCurrentLanguage() {
        return this.currentLang;
    }

    // Set current language
    setLanguage(lang) {
        this.currentLang = lang;
        localStorage.setItem('language', lang);
        this.applyLanguage(lang);
    }

    // Toggle between languages
    toggleLanguage() {
        const newLang = this.currentLang === 'en' ? 'ar' : 'en';
        this.setLanguage(newLang);
        return newLang;
    }

    // Get translation for a specific key (supports dot notation like category.key1.key2)
    translate(category, key) {
        try {
            let cat = translations[category];
            if (!cat) return key;

            // Handle nested keys (e.g., menu.dashboard)
            const keys = key.split('.');
            let value = cat[this.currentLang];

            for (const k of keys) {
                if (value && value[k]) {
                    value = value[k];
                } else {
                    value = null;
                    break;
                }
            }

            if (typeof value === 'string') return value;

            // Fallback to English
            value = cat[this.fallbackLang];
            for (const k of keys) {
                if (value && value[k]) {
                    value = value[k];
                } else {
                    value = null;
                    break;
                }
            }

            return typeof value === 'string' ? value : key;
        } catch (error) {
            console.warn('Translation error:', error);
            return key;
        }
    }

    // Apply language to the entire page
    applyLanguage(lang) {
        // Update HTML lang attribute
        const htmlElement = document.documentElement;
        if (htmlElement) {
            htmlElement.setAttribute('lang', lang);
        }

        // Update body direction
        const body = document.body;
        if (body) {
            if (lang === 'ar') {
                body.setAttribute('dir', 'rtl');
                body.classList.add('rtl');
            } else {
                body.setAttribute('dir', 'ltr');
                body.classList.remove('rtl');
            }
        }

        // Update all translatable elements
        document.querySelectorAll('[data-translate]').forEach(element => {
            const translateAttr = element.getAttribute('data-translate');
            const parts = translateAttr.split('.');
            const category = parts[0];
            const key = parts.slice(1).join('.');

            if (category && key) {
                const translation = this.translate(category, key);
                if (translation && typeof translation === 'string') {
                    element.textContent = translation;
                }
            }
        });

        // Specifically handle placeholders for inputs that don't use textContent
        document.querySelectorAll('[data-translate-placeholder]').forEach(element => {
            const translateAttr = element.getAttribute('data-translate-placeholder');
            const parts = translateAttr.split('.');
            const category = parts[0];
            const key = parts.slice(1).join('.');

            if (category && key) {
                const translation = this.translate(category, key);
                if (translation && typeof translation === 'string') {
                    element.setAttribute('placeholder', translation);
                }
            }
        });

        // Update language toggle button
        const langText = document.querySelector('.lang-text');
        if (langText) {
            langText.textContent = lang === 'en' ? 'EG' : 'AR';
        }

        const langIcon = document.querySelector('.lang-icon');
        if (langIcon) {
            langIcon.textContent = lang === 'en' ? '🇪🇬' : '🌐';
        }

        // Update page title if available
        const titleElement = document.querySelector('title[data-translate]');
        if (titleElement) {
            const translateAttr = titleElement.getAttribute('data-translate');
            const parts = translateAttr.split('.');
            const category = parts[0];
            const key = parts.slice(1).join('.');

            if (category && key) {
                const translation = this.translate(category, key);
                if (translation && typeof translation === 'string') {
                    document.title = translation;
                }
            }
        }
    }

    // Initialize language system
    init() {
        this.applyLanguage(this.currentLang);
    }
}

// Create global language manager instance
const langManager = new LanguageManager();

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { translations, LanguageManager, langManager };
}
